# Generated by Django 4.1.1 on 2022-12-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(max_length=10000, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
            ],
        ),
    ]
